/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/ai/skills/': RouteRecordInfo<'/posts/ai/skills/', '/posts/ai/skills', Record<never, never>, Record<never, never>>,
    '/posts/compiler/': RouteRecordInfo<'/posts/compiler/', '/posts/compiler', Record<never, never>, Record<never, never>>,
    '/posts/compiler2/': RouteRecordInfo<'/posts/compiler2/', '/posts/compiler2', Record<never, never>, Record<never, never>>,
    '/posts/compiler3/': RouteRecordInfo<'/posts/compiler3/', '/posts/compiler3', Record<never, never>, Record<never, never>>,
    '/posts/component/': RouteRecordInfo<'/posts/component/', '/posts/component', Record<never, never>, Record<never, never>>,
    '/posts/component10/': RouteRecordInfo<'/posts/component10/', '/posts/component10', Record<never, never>, Record<never, never>>,
    '/posts/component11/': RouteRecordInfo<'/posts/component11/', '/posts/component11', Record<never, never>, Record<never, never>>,
    '/posts/component12/': RouteRecordInfo<'/posts/component12/', '/posts/component12', Record<never, never>, Record<never, never>>,
    '/posts/component13/': RouteRecordInfo<'/posts/component13/', '/posts/component13', Record<never, never>, Record<never, never>>,
    '/posts/component14/': RouteRecordInfo<'/posts/component14/', '/posts/component14', Record<never, never>, Record<never, never>>,
    '/posts/component15/': RouteRecordInfo<'/posts/component15/', '/posts/component15', Record<never, never>, Record<never, never>>,
    '/posts/component16/': RouteRecordInfo<'/posts/component16/', '/posts/component16', Record<never, never>, Record<never, never>>,
    '/posts/component17/': RouteRecordInfo<'/posts/component17/', '/posts/component17', Record<never, never>, Record<never, never>>,
    '/posts/component2/': RouteRecordInfo<'/posts/component2/', '/posts/component2', Record<never, never>, Record<never, never>>,
    '/posts/component3/': RouteRecordInfo<'/posts/component3/', '/posts/component3', Record<never, never>, Record<never, never>>,
    '/posts/component4/': RouteRecordInfo<'/posts/component4/', '/posts/component4', Record<never, never>, Record<never, never>>,
    '/posts/component5/': RouteRecordInfo<'/posts/component5/', '/posts/component5', Record<never, never>, Record<never, never>>,
    '/posts/component6/': RouteRecordInfo<'/posts/component6/', '/posts/component6', Record<never, never>, Record<never, never>>,
    '/posts/component7/': RouteRecordInfo<'/posts/component7/', '/posts/component7', Record<never, never>, Record<never, never>>,
    '/posts/component8/': RouteRecordInfo<'/posts/component8/', '/posts/component8', Record<never, never>, Record<never, never>>,
    '/posts/component9/': RouteRecordInfo<'/posts/component9/', '/posts/component9', Record<never, never>, Record<never, never>>,
    '/posts/computed/': RouteRecordInfo<'/posts/computed/', '/posts/computed', Record<never, never>, Record<never, never>>,
    '/posts/create-app/': RouteRecordInfo<'/posts/create-app/', '/posts/create-app', Record<never, never>, Record<never, never>>,
    '/posts/debugger-vue-in-webstorm/': RouteRecordInfo<'/posts/debugger-vue-in-webstorm/', '/posts/debugger-vue-in-webstorm', Record<never, never>, Record<never, never>>,
    '/posts/diff/': RouteRecordInfo<'/posts/diff/', '/posts/diff', Record<never, never>, Record<never, never>>,
    '/posts/elpis/': RouteRecordInfo<'/posts/elpis/', '/posts/elpis', Record<never, never>, Record<never, never>>,
    '/posts/elpis2/': RouteRecordInfo<'/posts/elpis2/', '/posts/elpis2', Record<never, never>, Record<never, never>>,
    '/posts/elpis3/': RouteRecordInfo<'/posts/elpis3/', '/posts/elpis3', Record<never, never>, Record<never, never>>,
    '/posts/elpis4/': RouteRecordInfo<'/posts/elpis4/', '/posts/elpis4', Record<never, never>, Record<never, never>>,
    '/posts/elpis5/': RouteRecordInfo<'/posts/elpis5/', '/posts/elpis5', Record<never, never>, Record<never, never>>,
    '/posts/encapsulation-component/': RouteRecordInfo<'/posts/encapsulation-component/', '/posts/encapsulation-component', Record<never, never>, Record<never, never>>,
    '/posts/engineering/': RouteRecordInfo<'/posts/engineering/', '/posts/engineering', Record<never, never>, Record<never, never>>,
    '/posts/external-link-replacement/': RouteRecordInfo<'/posts/external-link-replacement/', '/posts/external-link-replacement', Record<never, never>, Record<never, never>>,
    '/posts/git-use/': RouteRecordInfo<'/posts/git-use/', '/posts/git-use', Record<never, never>, Record<never, never>>,
    '/posts/interview-szml/': RouteRecordInfo<'/posts/interview-szml/', '/posts/interview-szml', Record<never, never>, Record<never, never>>,
    '/posts/interview-szml-2/': RouteRecordInfo<'/posts/interview-szml-2/', '/posts/interview-szml-2', Record<never, never>, Record<never, never>>,
    '/posts/jeecg-table-empty-custom-render/': RouteRecordInfo<'/posts/jeecg-table-empty-custom-render/', '/posts/jeecg-table-empty-custom-render', Record<never, never>, Record<never, never>>,
    '/posts/js-writing/': RouteRecordInfo<'/posts/js-writing/', '/posts/js-writing', Record<never, never>, Record<never, never>>,
    '/posts/js-writing2/': RouteRecordInfo<'/posts/js-writing2/', '/posts/js-writing2', Record<never, never>, Record<never, never>>,
    '/posts/js-writing3/': RouteRecordInfo<'/posts/js-writing3/', '/posts/js-writing3', Record<never, never>, Record<never, never>>,
    '/posts/nestjs/': RouteRecordInfo<'/posts/nestjs/', '/posts/nestjs', Record<never, never>, Record<never, never>>,
    '/posts/reactivity/': RouteRecordInfo<'/posts/reactivity/', '/posts/reactivity', Record<never, never>, Record<never, never>>,
    '/posts/rebase/': RouteRecordInfo<'/posts/rebase/', '/posts/rebase', Record<never, never>, Record<never, never>>,
    '/posts/render/': RouteRecordInfo<'/posts/render/', '/posts/render', Record<never, never>, Record<never, never>>,
    '/posts/runtime-core/': RouteRecordInfo<'/posts/runtime-core/', '/posts/runtime-core', Record<never, never>, Record<never, never>>,
    '/posts/runtime-dom/': RouteRecordInfo<'/posts/runtime-dom/', '/posts/runtime-dom', Record<never, never>, Record<never, never>>,
    '/posts/scene/': RouteRecordInfo<'/posts/scene/', '/posts/scene', Record<never, never>, Record<never, never>>,
    '/posts/sse/': RouteRecordInfo<'/posts/sse/', '/posts/sse', Record<never, never>, Record<never, never>>,
    '/posts/text-node/': RouteRecordInfo<'/posts/text-node/', '/posts/text-node', Record<never, never>, Record<never, never>>,
    '/posts/typescript/': RouteRecordInfo<'/posts/typescript/', '/posts/typescript', Record<never, never>, Record<never, never>>,
    '/posts/vite-plugin/': RouteRecordInfo<'/posts/vite-plugin/', '/posts/vite-plugin', Record<never, never>, Record<never, never>>,
    '/posts/volta/': RouteRecordInfo<'/posts/volta/', '/posts/volta', Record<never, never>, Record<never, never>>,
    '/posts/vue-interview/': RouteRecordInfo<'/posts/vue-interview/', '/posts/vue-interview', Record<never, never>, Record<never, never>>,
    '/posts/watch/': RouteRecordInfo<'/posts/watch/', '/posts/watch', Record<never, never>, Record<never, never>>,
    '/posts/websocket/': RouteRecordInfo<'/posts/websocket/', '/posts/websocket', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/ai/skills/index.md': {
      routes: '/posts/ai/skills/'
      views: never
    }
    'pages/posts/compiler/index.md': {
      routes: '/posts/compiler/'
      views: never
    }
    'pages/posts/compiler2/index.md': {
      routes: '/posts/compiler2/'
      views: never
    }
    'pages/posts/compiler3/index.md': {
      routes: '/posts/compiler3/'
      views: never
    }
    'pages/posts/component/index.md': {
      routes: '/posts/component/'
      views: never
    }
    'pages/posts/component10/index.md': {
      routes: '/posts/component10/'
      views: never
    }
    'pages/posts/component11/index.md': {
      routes: '/posts/component11/'
      views: never
    }
    'pages/posts/component12/index.md': {
      routes: '/posts/component12/'
      views: never
    }
    'pages/posts/component13/index.md': {
      routes: '/posts/component13/'
      views: never
    }
    'pages/posts/component14/index.md': {
      routes: '/posts/component14/'
      views: never
    }
    'pages/posts/component15/index.md': {
      routes: '/posts/component15/'
      views: never
    }
    'pages/posts/component16/index.md': {
      routes: '/posts/component16/'
      views: never
    }
    'pages/posts/component17/index.md': {
      routes: '/posts/component17/'
      views: never
    }
    'pages/posts/component2/index.md': {
      routes: '/posts/component2/'
      views: never
    }
    'pages/posts/component3/index.md': {
      routes: '/posts/component3/'
      views: never
    }
    'pages/posts/component4/index.md': {
      routes: '/posts/component4/'
      views: never
    }
    'pages/posts/component5/index.md': {
      routes: '/posts/component5/'
      views: never
    }
    'pages/posts/component6/index.md': {
      routes: '/posts/component6/'
      views: never
    }
    'pages/posts/component7/index.md': {
      routes: '/posts/component7/'
      views: never
    }
    'pages/posts/component8/index.md': {
      routes: '/posts/component8/'
      views: never
    }
    'pages/posts/component9/index.md': {
      routes: '/posts/component9/'
      views: never
    }
    'pages/posts/computed/index.md': {
      routes: '/posts/computed/'
      views: never
    }
    'pages/posts/create-app/index.md': {
      routes: '/posts/create-app/'
      views: never
    }
    'pages/posts/debugger-vue-in-webstorm/index.md': {
      routes: '/posts/debugger-vue-in-webstorm/'
      views: never
    }
    'pages/posts/diff/index.md': {
      routes: '/posts/diff/'
      views: never
    }
    'pages/posts/elpis/index.md': {
      routes: '/posts/elpis/'
      views: never
    }
    'pages/posts/elpis2/index.md': {
      routes: '/posts/elpis2/'
      views: never
    }
    'pages/posts/elpis3/index.md': {
      routes: '/posts/elpis3/'
      views: never
    }
    'pages/posts/elpis4/index.md': {
      routes: '/posts/elpis4/'
      views: never
    }
    'pages/posts/elpis5/index.md': {
      routes: '/posts/elpis5/'
      views: never
    }
    'pages/posts/encapsulation-component/index.md': {
      routes: '/posts/encapsulation-component/'
      views: never
    }
    'pages/posts/engineering/index.md': {
      routes: '/posts/engineering/'
      views: never
    }
    'pages/posts/external-link-replacement/index.md': {
      routes: '/posts/external-link-replacement/'
      views: never
    }
    'pages/posts/git-use/index.md': {
      routes: '/posts/git-use/'
      views: never
    }
    'pages/posts/interview-szml/index.md': {
      routes: '/posts/interview-szml/'
      views: never
    }
    'pages/posts/interview-szml-2/index.md': {
      routes: '/posts/interview-szml-2/'
      views: never
    }
    'pages/posts/jeecg-table-empty-custom-render/index.md': {
      routes: '/posts/jeecg-table-empty-custom-render/'
      views: never
    }
    'pages/posts/js-writing/index.md': {
      routes: '/posts/js-writing/'
      views: never
    }
    'pages/posts/js-writing2/index.md': {
      routes: '/posts/js-writing2/'
      views: never
    }
    'pages/posts/js-writing3/index.md': {
      routes: '/posts/js-writing3/'
      views: never
    }
    'pages/posts/nestjs/index.md': {
      routes: '/posts/nestjs/'
      views: never
    }
    'pages/posts/reactivity/index.md': {
      routes: '/posts/reactivity/'
      views: never
    }
    'pages/posts/rebase/index.md': {
      routes: '/posts/rebase/'
      views: never
    }
    'pages/posts/render/index.md': {
      routes: '/posts/render/'
      views: never
    }
    'pages/posts/runtime-core/index.md': {
      routes: '/posts/runtime-core/'
      views: never
    }
    'pages/posts/runtime-dom/index.md': {
      routes: '/posts/runtime-dom/'
      views: never
    }
    'pages/posts/scene/index.md': {
      routes: '/posts/scene/'
      views: never
    }
    'pages/posts/sse/index.md': {
      routes: '/posts/sse/'
      views: never
    }
    'pages/posts/text-node/index.md': {
      routes: '/posts/text-node/'
      views: never
    }
    'pages/posts/typescript/index.md': {
      routes: '/posts/typescript/'
      views: never
    }
    'pages/posts/vite-plugin/index.md': {
      routes: '/posts/vite-plugin/'
      views: never
    }
    'pages/posts/volta/index.md': {
      routes: '/posts/volta/'
      views: never
    }
    'pages/posts/vue-interview/index.md': {
      routes: '/posts/vue-interview/'
      views: never
    }
    'pages/posts/watch/index.md': {
      routes: '/posts/watch/'
      views: never
    }
    'pages/posts/websocket/index.md': {
      routes: '/posts/websocket/'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
